tap "anomalyco/tap/opencode"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "nikitabobko/tap/aerospace"

brew "autoconf"
brew "btop"
brew "cmake"
brew "eza" # Better ls
brew "fastfetch"
brew "fd" # Easier find
brew "ffmpeg"
brew "fzf"
brew "gh" # Github client
brew "git"
brew "go"
brew "htop"
brew "hyperfine" Benchmarking tool
brew "imagemagick"
brew "lazygit"
brew "less" # Because Mac ships with outdated less
brew "lld@20"
brew "llvm@20"
brew "luarocks"
brew "mpv" # Media player
brew "neovim"
brew "ninja"
brew "node"
brew "opencode"
brew "pandoc-crossref"
brew "pandoc"
brew "python@3.13"
brew "python@3.14"
brew "ripgrep"
brew "rust"
brew "stow"
brew "tmux"
brew "urlview"
brew "uv"
brew "wget"
brew "yazi"
brew "zoxide" # Better cd

cask "appcleaner"
cask "discord"
cask "dropzone"
cask "font-hack-nerd-font"
cask "ghostty"
cask "hammerspoon"
cask "imageoptim"
cask "microsoft-teams"
cask "mullvad-vpn"
cask "nikitabobko/tap/aerospace"
cask "obsidian"
cask "raycast"
cask "telegram"
cask "visual-studio-code"
cask "zen"
cask "zoom"
