return {
	"stevearc/conform.nvim",
	event = { "BufWritePre" },
	cmd = { "ConformInfo" },
	keys = {
		{
			"<leader>bf",
			function()
				require("conform").format({
					lsp_fallback = "fallback",
					timeout_ms = 500,
				})
			end,
			mode = "n",
			desc = "Format buffer",
		},
	},
	opts = {
		formatters_by_ft = {
			lua = { "stylua" },
			python = { "ruff_format", "ruff_organize_imports" },
			javascript = { "biome" },
			typescript = { "biome" },
			tex = { "tex-fmt" },
			json = { "jq" },
			html = { "superhtml" },
			markdown = { "rumdl" },
			sh = { "shfmt" },
			sql = { "sqruff" },
			yml = { "yq" },
			zig = { "zigfmt" },
		},
		formatters = {
			rumdl = {
				inherit = true,
				append_args = {
					"--config",
					"MD060.enabled=true",
					"--config",
					"MD063.enabled=true",
					"--config",
					'MD063.style="sentence-case"',
					"--config",
					'MD003.style="atx"',
					"--config",
					'MD004.style="dash"',
					"--config",
					"global.line-length=95",
					"--config",
					'global.flavor="commonmark"',
					"--config",
					"MD013.line-length=95",
					"--config",
					"MD013.strict=true",
					"--config",
					"MD013.reflow=true",
					"--config",
					'MD049.style="underscore"',
					"--config",
					'MD050.style="underscore"',
				},
			},
		},
	},
}
